server:
  port: 84

spring:
  application:
    name: cloud-alibaba-consumer-order84

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

#消费者将去访问的微服务名称
server-url:
  nacos-user-service: http://cloud-alibaba-provider-payment


#激活sentinel对openfeign的支持
feign:
  sentinel:
    enabled: true
